# Generated by Django 5.2.14 on 2026-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart",
                    models.CharField(
                        choices=[("spotify", "Spotify"), ("billboard", "Billboard")],
                        max_length=20,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=120)),
                ("stat", models.CharField(blank=True, max_length=80)),
                ("emoji", models.CharField(blank=True, max_length=20)),
                ("meter", models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                "ordering": ["chart", "rank"],
            },
        ),
        migrations.CreateModel(
            name="Drama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=60)),
                ("emoji", models.CharField(blank=True, max_length=20)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FashionLook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("badge", models.CharField(blank=True, max_length=60)),
                ("emoji", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField()),
                ("shop_text", models.CharField(blank=True, max_length=120)),
                ("shop_url", models.URLField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breaking_news", models.TextField(blank=True)),
                ("ticker_items", models.TextField(blank=True)),
                ("award_title", models.CharField(blank=True, max_length=255)),
                ("award_meta", models.CharField(blank=True, max_length=255)),
                ("award_bullets", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=120)),
                ("read_time", models.CharField(default="5 min read", max_length=40)),
                ("excerpt", models.TextField()),
                ("emoji", models.CharField(blank=True, max_length=20)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=32)),
                ("category", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("meta", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
